#! /bin/bash

set -e

if [[ $(type -t git) != "file" ]]; then
  echo "Notice: git not found"
  if [[ $(type -t yum) == "file" ]]; then
    sudo yum -y install git
  else
    echo "Error: unable to install git"
    exit 1
  fi
fi

cd ~/workspace

mv dotfiles dotfiles$(date +%s)

git clone git@github.com:sclaret/dotfiles.git

cd dotfiles

./bootstrap/link.sh

