#! /bin/bash

set -e

cd ~/.ssh
mv id_rsa id_rsa$(date +%s)
mv id_rsa.pub id_rsa.pub$(date +%s)

uuid=$(openssl rand -base64 32 | shasum | cut -c 1-7) 
title="$USER@$HOSTNAME-$uuid"

ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""

key=$(cat ~/.ssh/id_rsa.pub)

if [[ -n $GITHUB_PASSWORD ]]; then
  ghpw=$GITHUB_PASSWORD
else
  read -s -p "Please enter Github password: " ghpw
fi 

curl \
    --user "sclaret:$ghpw" \
    --data "{\"title\":\"$title\", \"key\":\"$key\"}" \
    https://api.github.com/user/keys
